In [1]:
import numpy as np
import cv2

In [2]:
num_particles = 10
w = 15
h = 5

particles = np.array([
                np.random.randint(0, w, num_particles),
                np.random.randint(0, h, num_particles)
            ]).T
particles

array([[ 4,  4],
       [10,  4],
       [ 1,  2],
       [ 6,  0],
       [14,  4],
       [14,  3],
       [14,  3],
       [ 5,  3],
       [ 4,  3],
       [ 1,  3]])

In [3]:
weights = np.array([1./num_particles] * num_particles)
weights

array([ 0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1,  0.1])

In [4]:
inds = np.random.choice(num_particles, num_particles, p=weights)
inds

array([5, 9, 7, 5, 5, 4, 4, 6, 7, 0])

In [5]:
particles[inds]

array([[14,  3],
       [ 1,  3],
       [ 5,  3],
       [14,  3],
       [14,  3],
       [14,  4],
       [14,  4],
       [14,  3],
       [ 5,  3],
       [ 4,  4]])

In [6]:
for state in particles:
    x, y = state
    print x, y

4 4
10 4
1 2
6 0
14 4
14 3
14 3
5 3
4 3
1 3


In [7]:
tw = 4
f_row_start = 3
if tw % 2 == 0: f_row_start += 1
f_row_start

4

In [8]:
np.random.normal(0, 10, 1)[0]

-1.4935610409622284

In [9]:
np.sqrt(4)

2.0

In [16]:
np.insert(particles, 2, np.random.randint(0,10,10) , axis=1)

array([[ 4,  4,  2],
       [10,  4,  4],
       [ 1,  2,  2],
       [ 6,  0,  1],
       [14,  4,  5],
       [14,  3,  9],
       [14,  3,  5],
       [ 5,  3,  4],
       [ 4,  3,  2],
       [ 1,  3,  8]])

In [22]:
1e-4

0.0001